# Generated by Django 6.0.4 on 2026-05-02 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('especializacion', models.CharField(max_length=100)),
                ('numero_actividades_asignadas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ResponsableSala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioInscrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('capacidad', models.IntegerField()),
                ('ubicacion', models.CharField(max_length=100)),
                ('responsable', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestion_actividades.responsablesala')),
            ],
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('horario', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('duracion', models.IntegerField()),
                ('plazas_disponibles', models.IntegerField()),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_actividades.monitor')),
                ('sala_principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sala_principal_actividad', to='gestion_actividades.sala')),
                ('salas_secundarias', models.ManyToManyField(blank=True, related_name='salas_secundarias_actividad', to='gestion_actividades.sala')),
                ('usuarios_inscritos', models.ManyToManyField(to='gestion_actividades.usuarioinscrito')),
            ],
        ),
    ]
