# Generated by Django 6.0.4 on 2026-05-02 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_actividades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='usuarios_inscritos',
            field=models.ManyToManyField(blank=True, to='gestion_actividades.usuarioinscrito'),
        ),
    ]
