# Generated by Django 6.0.4 on 2026-05-14 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_actividades', '0002_alter_actividad_usuarios_inscritos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitor',
            name='numero_actividades_asignadas',
        ),
        migrations.AlterField(
            model_name='actividad',
            name='monitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='gestion_actividades.monitor'),
        ),
    ]
